<?php
function module_defs(){return [
'customers'=>['title'=>'Customer Register','table'=>'customers','number'=>null,'fields'=>[
 ['customer_name','Customer Name','text',1],['company_name','Company Name','text'],['contact_person','Contact Person','text'],['mobile','Mobile','text',1],['whatsapp','WhatsApp','text'],['email','Email','email'],['address','Address','textarea'],['area','Area','text'],['district','District','text'],['business_type','Business Type','text'],['customer_category','Category','text'],['assigned_marketer_id','Assigned Marketer ID','number'],['opening_balance','Opening Balance','number'],['credit_limit','Credit Limit','number'],['payment_terms','Payment Terms','text'],['notes','Notes','textarea'],['status','Status','select',0,['active','inactive']]]],
'suppliers'=>['title'=>'Supplier Register','table'=>'suppliers','fields'=>[['supplier_name','Supplier Name','text',1],['company_name','Company Name','text'],['contact_person','Contact Person','text'],['mobile','Mobile','text'],['email','Email','email'],['address','Address','textarea'],['opening_balance','Opening Balance','number'],['notes','Notes','textarea'],['status','Status','select',0,['active','inactive']]]],
'product_categories'=>['title'=>'Product Categories','table'=>'product_categories','fields'=>[['name','Category Name','text',1],['description','Description','textarea'],['status','Status','select',0,['active','inactive']]]],
'units'=>['title'=>'Unit Register','table'=>'units','fields'=>[['name','Unit Name','text',1],['symbol','Symbol','text',1],['status','Status','select',0,['active','inactive']]]],
'warehouses'=>['title'=>'Warehouse / Godown','table'=>'warehouses','fields'=>[['name','Warehouse Name','text',1],['address','Address','textarea'],['status','Status','select',0,['active','inactive']]]],
'products'=>['title'=>'Product Register','table'=>'products','fields'=>[['product_name','Product Name','text',1],['supplier_id','Supplier ID','number'],['supplier_grade','Supplier Grade','text'],['product_code','Unique Code','text',1],['category_id','Category ID','number'],['sku','SKU','text'],['unit_id','Unit ID','number'],['purchase_rate','Purchase Rate','number'],['sales_rate','Sales Rate','number'],['opening_stock','Opening Stock','number'],['current_stock','Current Stock','number'],['minimum_stock_level','Minimum Stock','number'],['description','Description','textarea'],['application','Application','textarea'],['image','Image Path','text'],['status','Status','select',0,['active','inactive']]]],'crm_leads'=>['title'=>'CRM Leads','table'=>'crm_leads','number'=>null,'fields'=>[['lead_no','Lead No','text'],['company_name','Lead/Company Name','text',1],['contact_person','Contact Person','text'],['mobile','Mobile','text'],['whatsapp','WhatsApp','text'],['email','Email','email'],['address','Address','textarea'],['product_interest','Product Interest','text'],['lead_source','Lead Source','text'],['assigned_marketer_id','Assigned Marketer ID','number'],['status','Status','select',0,['New','Contacted','Quotation Sent','Sample Sent','Negotiation','Order Confirmed','Lost','Follow-up Later']],['next_followup_date','Next Follow-up Date','date'],['notes','Notes','textarea']]],
'crm_followups'=>['title'=>'CRM Follow-ups','table'=>'crm_followups','fields'=>[['lead_id','Lead ID','number'],['customer_id','Customer ID','number'],['followup_date','Follow-up Date','date',1],['followup_type','Type','select',0,['Call','Meeting','Visit','WhatsApp','Email']],['notes','Notes','textarea'],['next_followup_date','Next Follow-up','date'],['status','Status','select',0,['Open','Done','Missed']]]],
'quotations'=>['title'=>'Quotations','table'=>'quotations','number'=>'quotation','fields'=>[['quotation_no','Quotation No','readonly'],['quotation_date','Date','date',1],['customer_id','Customer ID','number'],['lead_id','Lead ID','number'],['validity','Validity','text'],['payment_terms','Payment Terms','text'],['delivery_terms','Delivery Terms','text'],['subtotal','Subtotal','number'],['total_amount','Total Amount','number'],['remarks','Remarks','textarea'],['status','Status','select',0,['Draft','Sent','Accepted','Rejected','Converted']]]],
'sales_orders'=>['title'=>'Sales Orders','table'=>'sales_orders','number'=>'sales_order','approve'=>1,'fields'=>[['order_no','Order No','readonly'],['order_date','Date','date',1],['customer_id','Customer ID','number',1],['marketer_id','Marketer ID','number'],['deliveryman_id','Deliveryman ID','number'],['subtotal','Subtotal','number'],['discount','Discount','number'],['vat','VAT','number'],['total_amount','Total Amount','number'],['delivery_address','Delivery Address','textarea'],['delivery_date','Delivery Date','date'],['payment_terms','Payment Terms','text'],['remarks','Remarks','textarea'],['status','Status','select',0,['Draft','Pending Approval','Approved','Rejected','Partially Delivered','Delivered','Invoiced','Cancelled']]]],
'delivery_challans'=>['title'=>'Delivery Challans','table'=>'delivery_challans','number'=>'delivery_challan','fields'=>[['challan_no','Challan No','readonly'],['challan_date','Date','date',1],['customer_id','Customer ID','number',1],['sales_order_id','Sales Order ID','number'],['deliveryman_id','Deliveryman ID','number'],['vehicle_number','Vehicle No','text'],['driver_name','Driver Name','text'],['delivery_address','Delivery Address','textarea'],['receiver_name','Receiver Name','text'],['receiver_mobile','Receiver Mobile','text'],['status','Status','select',0,['Pending','Assigned','In Transit','Delivered','Partially Delivered','Returned','Cancelled']],['proof_file','Proof File','text'],['remarks','Remarks','textarea']]],
'sales_invoices'=>['title'=>'Sales Invoices','table'=>'sales_invoices','number'=>'sales_invoice','approve'=>1,'fields'=>[['invoice_no','Invoice No','readonly'],['invoice_date','Date','date',1],['customer_id','Customer ID','number',1],['sales_order_id','Sales Order ID','number'],['delivery_challan_id','Delivery Challan ID','number'],['subtotal','Subtotal','number'],['discount','Discount','number'],['vat','VAT','number'],['total_amount','Total Amount','number'],['paid_amount','Paid Amount','number'],['due_amount','Due Amount','number'],['payment_terms','Payment Terms','text'],['remarks','Remarks','textarea'],['status','Status','select',0,['Draft','Pending Approval','Approved','Rejected','Cancelled']]]],
'collections'=>['title'=>'Collections / Money Receipt','table'=>'collections','number'=>'collection','approve'=>1,'fields'=>[['receipt_no','Money Receipt No','readonly',1],['receipt_date','Date','date',1],['customer_id','Customer ID','number',1],['marketer_id','Marketer ID','number'],['payment_method','Payment Method','select',1,['Cash','Bank','Cheque','bKash','Nagad','Adjustment']],['cash_account_id','Cash Account','number'],['bank_account_id','Bank Account','number'],['cheque_number','Cheque No','text'],['cheque_date','Cheque Date','date'],['cheque_bank_name','Cheque Bank Name','text'],['cheque_amount','Cheque Amount','number'],['amount','Amount','number',1],['invoice_id','Against Invoice ID','number'],['discount_adjustment','Discount/Adjustment','number'],['remarks','Remarks','textarea'],['status','Status','select',0,['Pending','Approved','Rejected']]]],'inventory_movements'=>['title'=>'Inventory / Stock Movement','table'=>'inventory_movements','fields'=>[['movement_date','Date','date',1],['product_id','Product ID','number',1],['warehouse_id','Warehouse ID','number'],['movement_type','Movement Type','select',0,['Opening','Purchase','Sales Delivery','Sales Return','Purchase Return','Adjustment In','Adjustment Out']],['reference_type','Reference Type','text'],['reference_id','Reference ID','number'],['quantity_in','Qty In','number'],['quantity_out','Qty Out','number'],['rate','Rate','number'],['narration','Narration','textarea']]],
];}
function module_def($m){$defs=module_defs(); if(empty($defs[$m])){http_response_code(404);die('Module not found');} return $defs[$m];}
?>
