-- Color Heaven Office ERP: Sales Order backend tables
-- Backup database first. Import manually only. No data will be deleted by this script.

CREATE TABLE IF NOT EXISTS sales_orders (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    order_no VARCHAR(50) NOT NULL,
    order_date DATE NOT NULL,
    customer_id BIGINT UNSIGNED NULL,
    customer_name VARCHAR(190) NOT NULL,
    customer_mobile VARCHAR(50) NULL,
    customer_address TEXT NULL,
    previous_due DECIMAL(18,2) NOT NULL DEFAULT 0,
    marketer_id BIGINT UNSIGNED NULL,
    delivery_date DATE NULL,
    delivery_address TEXT NULL,
    delivery_person VARCHAR(150) NULL,
    vehicle_no VARCHAR(100) NULL,
    payment_terms VARCHAR(150) NULL,
    subtotal DECIMAL(18,2) NOT NULL DEFAULT 0,
    discount_amount DECIMAL(18,2) NOT NULL DEFAULT 0,
    transport_amount DECIMAL(18,2) NOT NULL DEFAULT 0,
    vat_amount DECIMAL(18,2) NOT NULL DEFAULT 0,
    grand_total DECIMAL(18,2) NOT NULL DEFAULT 0,
    remarks TEXT NULL,
    status VARCHAR(40) NOT NULL DEFAULT 'Draft',
    submitted_by BIGINT UNSIGNED NULL,
    submitted_at DATETIME NULL,
    approved_by BIGINT UNSIGNED NULL,
    approved_at DATETIME NULL,
    rejected_by BIGINT UNSIGNED NULL,
    rejected_at DATETIME NULL,
    approval_note TEXT NULL,
    created_by BIGINT UNSIGNED NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by BIGINT UNSIGNED NULL,
    updated_at DATETIME NULL,
    deleted_by BIGINT UNSIGNED NULL,
    deleted_at DATETIME NULL,
    delete_reason TEXT NULL,
    UNIQUE KEY uq_sales_orders_order_no (order_no),
    KEY idx_sales_orders_customer (customer_id),
    KEY idx_sales_orders_date (order_date),
    KEY idx_sales_orders_status (status),
    KEY idx_sales_orders_deleted (deleted_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS sales_order_items (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    sales_order_id BIGINT UNSIGNED NOT NULL,
    product_id BIGINT UNSIGNED NULL,
    product_name VARCHAR(190) NOT NULL,
    grade VARCHAR(120) NULL,
    bag_qty DECIMAL(18,3) NOT NULL DEFAULT 0,
    kg_per_bag DECIMAL(18,3) NOT NULL DEFAULT 25,
    total_kg DECIMAL(18,3) NOT NULL DEFAULT 0,
    rate DECIMAL(18,2) NOT NULL DEFAULT 0,
    line_total DECIMAL(18,2) NOT NULL DEFAULT 0,
    sort_order INT NOT NULL DEFAULT 0,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NULL,
    deleted_at DATETIME NULL,
    KEY idx_sales_order_items_order (sales_order_id),
    KEY idx_sales_order_items_product (product_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
