<?php
require_once __DIR__.'/includes/ch_ui_components.php';
ch_begin_app('order','Create Sales Order');
ch_wizard_steps(['Customer','Items','Delivery','Submit']);
?>
<form class="ch-card" data-demo><div class="ch-card-header"><div><h3>Sales Order Entry</h3><p>Responsive sales order interface with customer search, item rows, totals and approval actions.</p></div><span class="badge text-bg-warning">Draft</span></div>
<div class="ch-form-step active" data-step="1"><div class="ch-section-title">Customer & Order Information</div><div class="ch-form-grid"><div class="ch-field"><label>Order No</label><input class="form-control" value="SO-20260707-0001" readonly></div><div class="ch-field"><label>Date</label><input type="date" class="form-control" value="2026-07-07"></div><div class="ch-field"><label>Customer Search</label><input class="form-control" data-customer-search placeholder="Type customer name/mobile/company..." required></div><div class="ch-field"><label>Customer Mobile</label><input class="form-control" data-customer-mobile readonly></div><div class="ch-field full"><label>Customer Address</label><textarea class="form-control" data-customer-address rows="2"></textarea></div><div class="ch-field"><label>Previous Due</label><input class="form-control text-end" data-previous-due value="0.00" readonly></div><div class="ch-field"><label>Marketer</label><select class="form-select"><option>Rubayat Hamza</option><option>Md. Arifur Rahaman</option></select></div></div></div>
<div class="ch-form-step" data-step="2"><div class="ch-section-title d-flex justify-content-between align-items-center"><span>Voucher / Item Details</span><button type="button" class="btn btn-sm btn-ch-secondary" data-add-row="#orderItems" data-template="#orderRowTpl"><i class="bi bi-plus"></i> Add Row</button></div><div class="table-responsive"><table class="table ch-item-table"><thead><tr><th>Product</th><th>Grade</th><th>Bag Qty</th><th>Kg/Bag</th><th>Total Kg</th><th>Rate</th><th>Total Amount</th><th></th></tr></thead><tbody id="orderItems"><tr data-item-row><td><input class="form-control" data-product-search placeholder="Type product name/code" required></td><td><input class="form-control" data-grade readonly></td><td><input type="number" class="form-control" data-bag value="1"></td><td><input type="number" class="form-control" data-kg-bag value="25"></td><td><input class="form-control" data-total-kg readonly></td><td><input type="number" class="form-control" data-rate></td><td><input class="form-control text-end" data-line-total readonly></td><td><button type="button" class="btn btn-outline-danger btn-sm" data-remove-row><i class="bi bi-x"></i></button></td></tr></tbody></table></div></div>
<div class="ch-form-step" data-step="3"><div class="ch-section-title">Delivery & Extra Charges</div><div class="ch-form-grid"><div class="ch-field"><label>Delivery Date</label><input type="date" class="form-control" value="2026-07-08"></div><div class="ch-field"><label>Delivery Person</label><select class="form-select"><option>-- Select --</option><option>Md. Bajid Howlader</option></select></div><div class="ch-field"><label>Vehicle No</label><input class="form-control" placeholder="Dhaka Metro... "></div><div class="ch-field"><label>Payment Terms</label><input class="form-control" placeholder="Credit / Cash / 7 days"></div><div class="ch-field full"><label>Delivery Address</label><textarea class="form-control" rows="2"></textarea></div></div></div>
<div class="ch-form-step" data-step="4"><div class="ch-section-title">Summary & Approval</div><div class="ch-total-grid"><div class="ch-total-box"><span>Subtotal</span><input class="form-control text-end mt-2" data-subtotal value="0.00" readonly></div><div class="ch-total-box"><span>Discount</span><input type="number" class="form-control text-end mt-2" data-discount value="0"></div><div class="ch-total-box"><span>Transport</span><input type="number" class="form-control text-end mt-2" data-transport value="0"></div><div class="ch-total-box"><span>VAT</span><input type="number" class="form-control text-end mt-2" data-vat value="0"></div><div class="ch-total-box"><span>Grand Total</span><strong>৳ <span data-grand-text>0.00</span></strong><input type="hidden" data-grand></div></div><div class="ch-field mt-3"><label>Remarks</label><textarea class="form-control" rows="2"></textarea></div></div>
<div class="ch-sticky-actions"><button type="button" class="btn btn-outline-secondary">Save Draft</button><button class="btn btn-ch-primary">Submit for Approval</button></div></form>
<template id="orderRowTpl"><tr data-item-row><td><input class="form-control" data-product-search placeholder="Type product name/code" required></td><td><input class="form-control" data-grade readonly></td><td><input type="number" class="form-control" data-bag value="1"></td><td><input type="number" class="form-control" data-kg-bag value="25"></td><td><input class="form-control" data-total-kg readonly></td><td><input type="number" class="form-control" data-rate></td><td><input class="form-control text-end" data-line-total readonly></td><td><button type="button" class="btn btn-outline-danger btn-sm" data-remove-row><i class="bi bi-x"></i></button></td></tr></template>
<?php ch_module_list('Sales Order List','Customer'); ch_end_app(); ?>