<?php
/**
 * Voucher print router.
 * Existing ERP print buttons use voucher.php?module=...&id=...
 */
require_once __DIR__.'/includes/bootstrap.php';
require_login();
require_once __DIR__.'/includes/voucher_print.php';

$module = strtolower(trim((string)($_GET['module'] ?? '')));
$id = (int)($_GET['id'] ?? 0);

function vx_cols(string $table): array { try { return table_exists($table) ? table_columns($table) : []; } catch (Throwable $e) { return []; } }
function vx_has(string $table, string $col): bool { return in_array($col, vx_cols($table), true); }
function vx_pick(string $table, array $cols): string { $all = vx_cols($table); foreach($cols as $c) if(in_array($c,$all,true)) return $c; return ''; }
function vx_row(string $table, int $id): array { if(!$id || !table_exists($table)) return []; $st=db()->prepare("SELECT * FROM `$table` WHERE id=? LIMIT 1"); $st->execute([$id]); return $st->fetch() ?: []; }
function vx_customer_name($id): string { $c = vp_customer((int)$id); return vp_customer_name($c); }
function vx_product_name($id): string { return vp_product_name((int)$id); }
function vx_unit_name($id): string { if(!$id || !table_exists('units')) return (string)$id; $n=vx_pick('units',['name','unit_name','symbol']); if(!$n) return (string)$id; $st=db()->prepare("SELECT `$n` FROM units WHERE id=? LIMIT 1"); $st->execute([(int)$id]); return (string)($st->fetchColumn() ?: $id); }
function vx_print_css(): void { ?>
<style>
.vx{max-width:900px;margin:0 auto;background:#fff;color:#111;font-size:12px}.vx-title{text-align:center;font-weight:bold;font-size:20px;border-bottom:2px solid #111;margin-bottom:0}.vx-head{display:grid;grid-template-columns:1.2fr 1fr;border:1px solid #111;border-top:0}.vx-company{display:flex;gap:12px;padding:12px;border-right:1px solid #111}.vx-company img{width:90px;max-height:90px;object-fit:contain}.vx-company h3{margin:0;font-size:18px}.vx-meta{display:grid;grid-template-columns:1fr 1fr}.vx-meta div{padding:7px;min-height:45px;border-bottom:1px solid #111;border-right:1px solid #111}.vx-meta div:nth-child(even){border-right:0}.vx-box{border-left:1px solid #111;border-right:1px solid #111;border-bottom:1px solid #111;padding:10px;min-height:80px}.vx-table{width:100%;border-collapse:collapse;border-left:1px solid #111;border-right:1px solid #111}.vx-table th,.vx-table td{border-bottom:1px solid #111;border-right:1px solid #111;padding:7px;vertical-align:top}.vx-table th:last-child,.vx-table td:last-child{border-right:0}.num{text-align:right;white-space:nowrap}.vx-words{border:1px solid #111;border-top:0;padding:10px;min-height:85px}.vx-sign{display:grid;grid-template-columns:1fr 1fr 1fr;border:1px solid #111;border-top:0;min-height:85px}.vx-sign div{border-right:1px solid #111;text-align:center;padding:52px 8px 6px}.vx-sign div:last-child{border-right:0}.print-actions{max-width:900px;margin:0 auto 12px}@media print{.no-print,.sidebar,.topbar{display:none!important}.main,.content{margin:0!important;padding:0!important}.vx{max-width:none}body{background:#fff!important}}
</style>
<?php }
function vx_header(string $title, string $noLabel, string $no, string $dateLabel, string $date): void { $co=vp_company(); ?>
<div class="print-actions no-print"><button class="btn btn-primary" onclick="window.print()">Print / Save PDF</button> <a class="btn btn-light" href="javascript:history.back()">Back</a></div>
<div class="vx"><div class="vx-title"><?=vp_text($title)?></div><div class="vx-head"><div class="vx-company"><img src="<?=vp_text($co['logo'])?>" alt="Logo"><div><h3><?=vp_text($co['name'])?></h3><div><?=vp_text($co['address'])?></div><div>E-Mail : <?=vp_text($co['email'])?></div><small><?=vp_text($co['tagline'])?></small></div></div><div class="vx-meta"><div><span><?=vp_text($noLabel)?></span><br><strong><?=vp_text($no)?></strong></div><div><span><?=vp_text($dateLabel)?></span><br><strong><?=vp_text(vp_date($date))?></strong></div><div><span>Reference</span><br></div><div><span>Prepared By</span><br><?=vp_text(user()['full_name'] ?? '')?></div></div></div>
<?php }
function vx_footer(string $companyName='Color Heaven'): void { ?>
<div class="vx-sign"><div>Customer / Receiver Signature</div><div>Prepared by<br><br>Checked by</div><div>for <?=vp_text($companyName)?><br><br>Authorised Signatory</div></div><div style="text-align:center;margin-top:8px">This is a Computer Generated Voucher</div></div>
<?php }
function render_collection_voucher(int $id): void {
    require_perm('collections.view'); if(!table_exists('collections')){echo '<div class="alert alert-warning">Collection table not found.</div>';return;} $r=vx_row('collections',$id); if(!$r){echo '<div class="alert alert-warning">Collection voucher not found.</div>';return;}
    $noCol=vx_pick('collections',['receipt_no','voucher_no','collection_no']);$dateCol=vx_pick('collections',['receipt_date','collection_date','created_at']);$custCol=vx_pick('collections',['customer_id']);$amountCol=vx_pick('collections',['amount','received_amount','total_amount']);$methodCol=vx_pick('collections',['payment_method','collection_method','mode']);$remarksCol=vx_pick('collections',['remarks','notes']);
    $no=$noCol?($r[$noCol]??$id):$id;$date=$dateCol?($r[$dateCol]??''):'';$amount=$amountCol?(float)($r[$amountCol]??0):0;$method=$methodCol?($r[$methodCol]??'Receipt'):'Receipt';$customer=$custCol?vx_customer_name($r[$custCol]??0):'';$co=vp_company();$bank=[];foreach(['bank_name'=>'Bank','bank_account_id'=>'Bank Account','cheque_bank_name'=>'Cheque Bank','cheque_number'=>'Cheque No','cheque_date'=>'Cheque Date','transaction_id'=>'Txn ID'] as $col=>$label){if(vx_has('collections',$col)&&!empty($r[$col]))$bank[]=$label.': '.$r[$col];}
    vx_print_css();vx_header('MONEY RECEIPT','Receipt No.',$no,'Dated',$date);?><div class="vx-box"><strong>Received From</strong><br><?=vp_text($customer)?></div><table class="vx-table"><thead><tr><th>Particulars</th><th>Payment Mode</th><th>Bank / Cheque Details</th><th class="num">Amount</th></tr></thead><tbody><tr><td><?=vp_text($remarksCol?($r[$remarksCol]??'Collection received'):'Collection received')?></td><td><?=vp_text($method)?></td><td><?=vp_text(implode(' | ',$bank))?></td><td class="num"><?=vp_money($amount)?></td></tr><tr><td colspan="3" class="num"><strong>Total</strong></td><td class="num"><strong>TK <?=vp_money($amount)?></strong></td></tr></tbody></table><div class="vx-words"><div>Amount in words</div><strong><?=vp_text(vp_bdt_words($amount))?></strong></div><?php vx_footer($co['name']);
}
function render_inventory_voucher(int $id): void {
    require_perm('inventory_movements.view'); if(!table_exists('inventory_movements')){echo '<div class="alert alert-warning">Inventory table not found.</div>';return;} $r=vx_row('inventory_movements',$id); if(!$r){echo '<div class="alert alert-warning">Inventory voucher not found.</div>';return;}
    $dateCol=vx_pick('inventory_movements',['movement_date','date','created_at']);$prodCol=vx_pick('inventory_movements',['product_id']);$typeCol=vx_pick('inventory_movements',['movement_type','type']);$refTypeCol=vx_pick('inventory_movements',['reference_type']);$refIdCol=vx_pick('inventory_movements',['reference_id']);$qtyInCol=vx_pick('inventory_movements',['quantity_in','qty_in']);$qtyOutCol=vx_pick('inventory_movements',['quantity_out','qty_out']);$rateCol=vx_pick('inventory_movements',['rate']);$noteCol=vx_pick('inventory_movements',['narration','remarks','notes']);$whCol=vx_pick('inventory_movements',['warehouse_id']);$co=vp_company();
    vx_print_css();vx_header('INVENTORY VOUCHER','Voucher No.',$id,'Dated',$dateCol?($r[$dateCol]??''):'');?><div class="vx-box"><strong>Inventory / Stock Movement</strong><br>Reference: <?=vp_text(($refTypeCol?($r[$refTypeCol]??''):'').' '.($refIdCol?($r[$refIdCol]??''):''))?></div><table class="vx-table"><thead><tr><th>Product</th><th>Warehouse</th><th>Movement Type</th><th class="num">Qty In</th><th class="num">Qty Out</th><th class="num">Rate</th><th>Remarks</th></tr></thead><tbody><tr><td><?=vp_text($prodCol?vx_product_name($r[$prodCol]??0):'')?></td><td><?=vp_text($whCol?($r[$whCol]??''):'')?></td><td><?=vp_text($typeCol?($r[$typeCol]??''):'')?></td><td class="num"><?=vp_qty($qtyInCol?($r[$qtyInCol]??0):0)?></td><td class="num"><?=vp_qty($qtyOutCol?($r[$qtyOutCol]??0):0)?></td><td class="num"><?=vp_money($rateCol?($r[$rateCol]??0):0)?></td><td><?=vp_text($noteCol?($r[$noteCol]??''):'')?></td></tr></tbody></table><div class="vx-words"><strong>Note</strong><br>This voucher is generated from inventory movement record.</div><?php vx_footer($co['name']);
}
function render_product_voucher(int $id): void {
    require_perm('products.view'); if(!table_exists('products')){echo '<div class="alert alert-warning">Products table not found.</div>';return;} $r=vx_row('products',$id); if(!$r){echo '<div class="alert alert-warning">Product not found.</div>';return;}
    $name=vx_pick('products',['product_name','name','description']);$code=vx_pick('products',['product_code','unique_code','code']);$sku=vx_pick('products',['sku']);$unit=vx_pick('products',['unit_id']);$alt=vx_pick('products',['alternative_unit_id','alt_unit_id']);$altQty=vx_pick('products',['alternative_unit_qty','alt_unit_qty']);$baseQty=vx_pick('products',['base_qty_per_alternative_unit','base_qty_per_alt_unit','conversion_qty']);$stock=vx_pick('products',['current_stock']);$min=vx_pick('products',['minimum_stock_level','minimum_stock']);$rate=vx_pick('products',['sales_rate','price']);$status=vx_pick('products',['status']);$co=vp_company();
    vx_print_css();vx_header('PRODUCT PROFILE','Product ID',$id,'Dated',date('Y-m-d'));?><div class="vx-box"><strong><?=vp_text($name?($r[$name]??''):'Product')?></strong><br>Code: <?=vp_text($code?($r[$code]??''):'')?> | SKU: <?=vp_text($sku?($r[$sku]??''):'')?></div><table class="vx-table"><tbody><tr><th>Base Unit</th><td><?=vp_text($unit?vx_unit_name($r[$unit]??0):'')?></td><th>Alternative Unit</th><td><?=vp_text($alt?vx_unit_name($r[$alt]??0):'')?></td></tr><tr><th>Alternative Qty</th><td><?=vp_text($altQty?($r[$altQty]??''):'')?></td><th>Base Qty per Alt Unit</th><td><?=vp_text($baseQty?($r[$baseQty]??''):'')?></td></tr><tr><th>Current Stock</th><td><?=vp_text($stock?($r[$stock]??0):0)?></td><th>Minimum Stock</th><td><?=vp_text($min?($r[$min]??0):0)?></td></tr><tr><th>Sales Rate</th><td><?=vp_money($rate?($r[$rate]??0):0)?></td><th>Status</th><td><?=vp_text($status?($r[$status]??''):'')?></td></tr></tbody></table><div class="vx-words"><strong>Note</strong><br>This product profile includes alternative unit and conversion details when available.</div><?php vx_footer($co['name']);
}

$map=['sales_orders'=>'order','sales_order'=>'order','orders'=>'order','order'=>'order','delivery_challans'=>'delivery','delivery_challan'=>'delivery','delivery_notes'=>'delivery','delivery_note'=>'delivery','sales_invoices'=>'invoice','sales_invoice'=>'invoice','invoices'=>'invoice','invoice'=>'invoice'];
$title='Voucher Print';include __DIR__.'/includes/header.php';
if(isset($map[$module])){ vp_render($map[$module], $id); }
elseif(in_array($module,['collections','collection','money_receipt','money_receipts'],true)){ render_collection_voucher($id); }
elseif(in_array($module,['inventory_movements','inventory_movement','inventory','stock_movement'],true)){ render_inventory_voucher($id); }
elseif(in_array($module,['products','product'],true)){ render_product_voucher($id); }
else { echo '<div class="alert alert-warning">This voucher module does not have a printable format yet.</div><a class="btn btn-light" href="javascript:history.back()">Back</a>'; }
include __DIR__.'/includes/footer.php';
